# Generated by Django 3.2.6 on 2021-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='cat', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
